#!/usr/bin/env python3
"""生成 B 站 Cookie 文件（Netscape 格式）"""

cookies = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file is generated by yt-dlp.  Do not edit.

.bilibili.com	TRUE	/	FALSE	0	enable_web_push	DISABLE
.bilibili.com	TRUE	/	FALSE	0	DedeUserID	335603307
.bilibili.com	TRUE	/	FALSE	0	DedeUserID__ckMd5	3461f2740cab9123
.bilibili.com	TRUE	/	FALSE	0	home_feed_column	5
.bilibili.com	TRUE	/	FALSE	0	header_theme_version	OPEN
.bilibili.com	TRUE	/	FALSE	0	theme-tip-show	SHOWED
.bilibili.com	TRUE	/	FALSE	0	buvid4	D4CF1757-6D15-4F5D-0686-9D61BCAA73F968992-024071303-gQz+zB+c9YT9sj6Aew6IOg%3D%3D
.bilibili.com	TRUE	/	FALSE	0	buvid3	F6718476-8516-BE69-3F48-CECBD723749704905infoc
.bilibili.com	TRUE	/	FALSE	1814192584	b_nut	1752399404
.bilibili.com	TRUE	/	FALSE	0	_uuid	659A23C4-D3106-AF99-C172-9810C6A9E9B2916187infoc
.bilibili.com	TRUE	/	FALSE	0	rpdid	0zbfAHyv5v|rHZyK5CT|waJ|3w1UXq1V
.bilibili.com	TRUE	/	FALSE	0	buvid_fp	57c35ca15c3f60a492066df35222e26c
.bilibili.com	TRUE	/	FALSE	0	ogv_device_support_dolby	0
.bilibili.com	TRUE	/	FALSE	0	ogv_device_support_hdr	0
.bilibili.com	TRUE	/	FALSE	0	bsource	search_bing
.bilibili.com	TRUE	/	FALSE	0	LIVE_BUVID	AUTO2317820449519766
.bilibili.com	TRUE	/	FALSE	0	bili_ticket	eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODI3NDM2ODcsImlhdCI6MTc4MjQ4NDQyNywicGx0IjotMX0.HrOM91rE8l8HvOyl0QGWG_4xHHuPazQsjG2Y0iS-M4U
.bilibili.com	TRUE	/	FALSE	1782743627	bili_ticket_expires	1782743627
.bilibili.com	TRUE	/	FALSE	1798036720	SESSDATA	c4ef86e7%2C1798036720%2C9db79%2A61CjDemnGRvB39_-I7sxpItmmHbczhy98RpFqrZP0Ab7HheBkiMZkescUKVFK7Mp8Kt3oSVjVmTUtYM19aTGQySl9DbklEa01uRjFHdks2S1BrQndfb3lsVVAyNXpsbVpjRGFzQmhGVzA3NnlxRmhCaHR0Z2R6WHFvRWFVQXY2MnY3dEFleXNVa0N3IIEC
.bilibili.com	TRUE	/	FALSE	0	bili_jct	d12efe14175ad0eeb6633e57f603c0d2
.bilibili.com	TRUE	/	FALSE	0	sid	851y4taf
.bilibili.com	TRUE	/	FALSE	0	CURRENT_QUALITY	80
.bilibili.com	TRUE	/	FALSE	0	PVID	1
.bilibili.com	TRUE	/	FALSE	0	bp_t_offset_335603307	1218979884030754816
.bilibili.com	TRUE	/	FALSE	0	theme-avatar-tip-show	SHOWED
.bilibili.com	TRUE	/	FALSE	0	CURRENT_FNVAL	4048
.bilibili.com	TRUE	/	FALSE	0	browser_resolution	2552-982
.bilibili.com	TRUE	/	FALSE	0	b_lsid	28384A96_19F0E99CF44
"""

with open('bilibili_cookies.txt', 'w', encoding='utf-8', newline='\n') as f:
    f.write(cookies)

print("Cookie file created successfully: bilibili_cookies.txt")
